### ISSUE TITLE
Installation success report

### ISSUE THREAD

**Issue by vielmetti** [lmorchard/fossilizer#1]
I have `fossilizer` up and running on a `localhost` install on my MacBook Air under macOS.

A few notes.

If you are not used to Rust, then you might take a moment to remember that the build command is `cargo build`, and you might be poking around a little before you found the `target/debug` directory.

`fossilizer import` takes `gzip` files. If your archives appear as plain `tar` files you have to `gzip` them first before importing them.

It's a static site, so any static site serving system should work. I used `python3 -m http.server <port>`. You might want something more fancy than that.

Site search depends on `pagefind`, which was new to me (and worth learning about), see https://pagefind.app for the full story, but I built the index with `mkdir pagefind; ~/.cargo/bin/pagefind --source . --bundle-dir pagefind`.

I am not sure that everything works the same way it does for @lmorchard  but I'm happy to have access to my archives.

**Comment by lmorchard** [comment]
Possibly handy news: I've gotten automated release builds of this thing working, so you can download a pre-build binary and not have to build it yourself! Also, a rough first draft of usage instructions:

https://github.com/lmorchard/fossilizer/blob/main/README.md
