### ISSUE TITLE
bug? search overlay does not scroll

### ISSUE THREAD

**Issue by vielmetti** [lmorchard/fossilizer#3]
Browser is either Safari or Chrome on an M1 MacBook Air.

I get back results from pagefind just fine, but the
scrollbar at the right doesn't seem to scroll the pagefind
overlay at all, so I can't look at all of them.

I know they are there, because when I make the font size
smaller the results show up with a "load more" type dialogue
at the bottom.

Normal date pages load just fine, and there's a proper
infinite scroll on those.

---

I hate to report this as a bug because it might be any number of things
that aren't wrong with the code itself, but maybe it's a bug, I don't know.

**Comment by vielmetti** [comment]
Some more info from a debug session:

I'm getting 404 errors on 

/vendor/bootstrap.bundle.min.js.map
/vendor/bootstrap.min.css.map

None of the docs I see reference these map files, so I'm wondering if there's a step I'm missing.

**Comment by vielmetti** [comment]
Also noted: 

When I search, I get results, but the scrollbar doesn't scroll the search results.
What it does seem to scroll is the underlying date-based results.

next to try Firefox as the browser....

**Comment by vielmetti** [comment]
No difference in behavior on Firefox. I'll see about capturing a screencast.

**Comment by vielmetti** [comment]
An animated GIF of the interaction

![Fossilizer Index](https://github.com/lmorchard/fossilizer/assets/35047/11b8f76a-f19b-465f-a71c-1adea24f53f8)

**Comment by lmorchard** [comment]
Hmm, yeah, this is *probably* because I stuck the search widget into [a `position: fixed` bootstrap nav bar element](https://github.com/lmorchard/fossilizer/blob/main/src/resources/templates/layout.html#L20) and don't have any kind of overflow scroll set on the search results 🤔
