### ISSUE TITLE
Darwin: "Error: Is a directory (os error 21)" on "fossilizer import ~/Downloads/hachyderm-20240411.tar"

### ISSUE THREAD

**Issue by vielmetti** [lmorchard/fossilizer#31]
System is Safari, MacOS Ventura 13.6.6. My Mastodon instance is hachyderm.io (one of them at least).

Download an archive, but helpfully (?) Safari untars the file, so I have to re-tar it for fossilizer.

```
% fossilizer import ~/Downloads/hachyderm-20240411.tar 
[2024-04-11T23:43:19Z INFO  fossilizer::cli::import] Importing "/Users/emv/Downloads/hachyderm-20240411.tar"
[2024-04-11T23:43:21Z INFO  fossilizer::mastodon] Found 1125 items
[2024-04-11T23:43:21Z INFO  fossilizer::db::activities] Imported 500 items
[2024-04-11T23:43:21Z INFO  fossilizer::db::activities] Imported 1000 items
Error: Is a directory (os error 21)
```

```
> ~/src/github.com/lmorchard/fossilizer/target/debug/fossilizer -V    
fossilizer 0.2.0
```

**Comment by vielmetti** [comment]
Same result when I build from source and when I use the provided binary.

**Comment by lmorchard** [comment]
Hmm, that's an unexpected error... guessing something tried to write a file where there was already a directory, but that's weird

You *might* want to try deleting any existing build or data directory (`rm -rf ./build ./data`) and try a `fossilizer init` and then another `import` from scratch?

I'm going to scratch my head a bit at where that error might have come from and see if I can add some better error reporting.

**Comment by vielmetti** [comment]
ok, problem avoided, and a possible diagnosis:

first, Safari helpfully (?) expands out zip files when you download them, but you can avoid that with ctrl-click and then "Download linked file"

second, the linked file is a .zip file which works just fine I guess (no errors on import); the error that I got above happened after I tried to import a tar file that had been created from the expanded out zip file.

The workaround is easy enough and I blame my browser not your code.
