### ISSUE TITLE
Explore alternative client-side search systems

### ISSUE THREAD

**Issue by lmorchard** [lmorchard/fossilizer#8]
[pagefind](https://pagefind.app/) is the initial choice for client-side local search in fossilizer. It has a few drawbacks - e.g. it searches for whole pages, not for anchor links within pages for individual posts.

There are other client-side search projects - e.g. [tinysearch](https://github.com/tinysearch/tinysearch). Maybe another one of these would work better in this project, especially if [it can be embedded in the fossilizer executable](https://github.com/lmorchard/fossilizer/issues/7).

**Comment by bglw** [comment]
_(Pagefind 1.0 includes searching for anchor links within pages, and the current alpha contains most of the requisite data to reconstruct this in the client)_

**Comment by bglw** [comment]
👋 Just dropping in to say [Pagefind v1.0.0](https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0) now supports sub results out of the box 🙂

**Comment by lmorchard** [comment]
> 👋 Just dropping in to say [Pagefind v1.0.0](https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0) now supports sub results out of the box 🙂

🎉  ooh, thanks for dropping in with that! Turns out all I need to do is neglect a project for a month or two for things to improve! 😅

**Comment by lmorchard** [comment]
Going to close this, for now, since pagefind has gained more granular results
